baseURL = "https://trophysports.net/"
languageCode = "en-us"
title = "Trophy Sports"
theme = "graysx"

[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Sign Up"
  URL = "#signup"
  weight = 2